use_frameworks!

platform :ios, '9.0'

target 'NWReactNative_Example' do
  pod 'NWReactNative', :path => '../'

  target 'NWReactNative_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
